### ISSUE TITLE
can we run on pi os or ubuntu os 

### ISSUE THREAD

**Issue by tomriddle54** [shunyaos/shunyaface#2]

**Comment by shunyaos** [comment]
Hi ,

Thanks for your query .

**Can we run this on pi OS or Ubuntu I have laptop so getting errors :** Currently only on Shunya ,there is a lot of system engineering behind the speed ,can't optimise raspbian or Ubuntu so much , but you can run Ubuntu /debian commands directly on this os . If you encounter issues we will support .


**Any one interested in converting this code in python.:**
We will offer python and js API for this code very soon .Python api is number 1 demand so it will happen soon.

**How to detect multi face in one frame currently I am getting only one bonding box if there are two person in one frame:**

Multi person API is not released yet ,noted will add to list .

**In Database API what is the database like mongo, mysql when I call add_face() where it adds facial features.**
:Writes to a file . Database support will be added .

**How many fps are you getting on detecting face and recognition it with 128 points is there any demo code for it.**
The recognition fps is close to the detect library , but code needs a lot more optimisation to hit 98% + accuracy . Will release demo code after that .

**Comment by syedmustafa54** [comment]
thanks for the quick reply.
If I want to add multi-face my self how can I modify the mtcnn file I think I Just need to add for loop to get the work done.
I am not getting the freedom to do anything on this code so that's why asked you about ubuntu or pi os don't know what's inside `sudo opkg install shunyaface` where its install if I want to contribute or modify it. So can you please provide full source code of shunyaface so I can run it on any os 
I have worked on 512 points and its accurate so if posibble let's change this to 512

**Comment by shunyaos** [comment]
Thanks , we don't plan to release the source anytime soon . We intend to license this code to developers who  who want to develop AI Face applications but don't know or want to learn AI themselves.

Also MTCNN is heavily modified specially P -Net so it tough for others to understand unless we explain .

About 512 points : There are trade -offs , we have a team working on 512 we may release API for  that if it  works better at a later time .

**Comment by tomriddle54** [comment]
Hope this project gets fully open source :smile: and free to use
